esphome:
  name: livingroom
esp8266:
  board: esp01_1m

logger:

api:
  password: "123456"

ota:
  password: "123456"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "living room fallback hostpot"
    password: "12345678"


captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

external_components:
  - source: github://oxan/esphome-stream-server

stream_server:
  uart_id: uart_bus
  port: 1234
